---
title: "PracticalMachineLearning"
author: "SivaguruB"
date: "October 23, 2015"
output: 
  html_document: 
    theme: readable
---

Practical Machine Learning - Prediction Assignment Writeup

For this assignment I made use of the provided data from the Coursera Website and also i loaded the neccessary packages needed to get the requires output.

library(Hmisc)
library(caret)
library(randomForest)
library(foreach)
library(doParallel)
set.seed(2048)
options(warn=-1)

The datas are loaded both from the provided training and testing .csv files.Some values contained a "#DIV/0!" which are all replaced with an NA values here.

training_data <- read.csv("pml-training.csv", na.strings=c("#DIV/0!") )
evaluation_data <- read.csv("pml-testing.csv", na.strings=c("#DIV/0!") )

I also casted all columns 8 to the end to be numeric.

for(i in c(8:ncol(training_data)-1)) {training_data[,i] = as.numeric(as.character(training_data[,i]))}

for(i in c(8:ncol(evaluation_data)-1)) {evaluation_data[,i] = as.numeric(as.character(evaluation_data[,i]))}

Though some columns were blank that will leads to wrong prediction I utilised the feature_set here.

feature_set <- colnames(training_data[colSums(is.na(training_data)) == 0])[-(1:7)]
model_data <- training_data[feature_set]
feature_set

We now have the model data built from our feature set.

idx <- createDataPartition(y=model_data$classe, p=0.75, list=FALSE )
training <- model_data[idx,]
testing <- model_data[-idx,]

Now I am gonna build 5 random forests with 150 trees each by making use of parallel processing.

registerDoParallel()
x <- training[-ncol(training)]
y <- training$classe

rf <- foreach(ntree=rep(150, 6), .combine=randomForest::combine, .packages='randomForest') %dopar% {
randomForest(x, y, ntree=ntree) 
}

To provide error reports for both training and test data.

predictions1 <- predict(rf, newdata=training)
confusionMatrix(predictions1,training$classe)  ##Error Report


predictions2 <- predict(rf, newdata=testing)
confusionMatrix(predictions2,testing$classe)  ##Error Report

Test Data Submit

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}


x <- evaluation_data
x <- x[feature_set[feature_set!='classe']]
answers <- predict(rf, newdata=x)
pml_write_files(answers)
